Comment-out juila tests on CI

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -97,10 +97,10 @@ jobs:
         run: nix develop -c just test-python-bindings --color=yes
         if: runner.os == 'Linux'
 
-      - name: Test Julia in development environment
-        continue-on-error: true
-        run: |
-          nix develop -c just test-julia           --color=yes
-          if ! [[ "$(which julia)" == */nix/store* ]]; then echo " *** FAILING BECAUSE JULIA IS NOT PROVIDED BY NIX ***"; false; fi
-        #run: nix-shell --argstr py ${{ matrix.py }} --run "just test-julia           --color=yes"
-        if: runner.os == 'Linux'
+      # - name: Test Julia in development environment
+      #   continue-on-error: true
+      #   run: |
+      #     nix develop -c just test-julia           --color=yes
+      #     if ! [[ "$(which julia)" == */nix/store* ]]; then echo " *** FAILING BECAUSE JULIA IS NOT PROVIDED BY NIX ***"; false; fi
+      #   #run: nix-shell --argstr py ${{ matrix.py }} --run "just test-julia           --color=yes"
+      #   if: runner.os == 'Linux'
